---
driver:
  name: ec2
  instance_type: t2.medium
  security_group_ids: ["sg-a1c3b1db"]
  subnet_id: subnet-46b55431
  aws_ssh_key_id: <%= ENV["EC2_SSH_KEY_NAME"] %>

transport:
  ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[habitat_workstation::default]
    verifier:
      inspec_tests:
        - test/recipes/default_test.rb
    attributes:
      hab:
        version: none
  - name: install_hab
    run_list:
      - recipe[habitat_workstation::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      hab:
        version: 0.14.0/20161212214220